services:
  - type: web
    name: herbario-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/main/server.js
    envVars:
      - key: NODE_ENV
        value: production